when@dev:
    liip_imagine:
        resolvers:
            default:
                web_path:
                    web_root: "%kernel.project_dir%/public"
                    cache_prefix: "media/cache"
        loaders:
            default:
                filesystem:
                    data_root: "%kernel.project_dir%/private"

liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "imagick"

    # define your filter sets under this option
    filter_sets:

aropixel_admin:
    filter_sets:

